### ISSUE TITLE
x22i keccak 

### ISSUE THREAD

**Issue by KL0nLutiy** [fancyIX/sgminer-phi2-branch#106]
There is 2 known patterns that used for keccak kernel. The old one that is used in x22i now and newer one that was implemented by wolf I think. The second one used by avermore in x16r algo: https://github.com/brian112358/avermore-miner/blob/43e36dff5c21ad1ba98ef4b0efa07592780028d8/kernel/x16.cl#L993
This pattern is used by lycl miner:
https://github.com/CryptoGraphics/lyclMiner/blob/master/kernels/keccakF1600/keccakF1600.cl
And also it used by Ethash kernel: 
https://github.com/ethereum-mining/ethminer/blob/16e214428ddfc0954df10ba3a728149d68409606/libethash-cl/kernels/cl/ethash.cl#L87

I did a benchmark of this 2 patterns and the old one seems to be faster, but not sure why. Maybe this info will be useful for further x22i performance improvements.

**Comment by fancyIX** [comment]
@KL0nLutiy , did you run CodeXL on them? Which one has less vgpr usage and more occupancy? Anyone has vgpr spill. Any LDS banck conflicts?

**Comment by fancyIX** [comment]
Won't fix
