### ISSUE TITLE
GPU Hangs

### ISSUE THREAD

**Issue by ricky24theman** [fancyIX/sgminer-phi2-branch#110]
I am mining AGM (PHI2) on a Windows 7 machine with a XFX RX580. When I start the miner it runs fine for 2-7 minutes then it declares the tread sick, then dead or hung. The error is shown in the following screenshot. http://prntscr.com/lh3go2

**Comment by fancyIX** [comment]
@ricky24theman Thanks for letting me know. Did it hang each time you run it? What parameter you use to reproduce the problem? Can you add "--debug --log-file log.txt" and upload your log.txt here? I will test it for longer run on my 580 rig later today.

**Comment by fancyIX** [comment]
@ricky24theman Also, the hashrate shown in the screenshot doesn't seem right. For phi2 rx 580 should be about 3.7mhs at full clock (you need "-w 256 -I 22")

**Comment by ricky24theman** [comment]
Yes it hangs every time I run it. I have tried lowering the intensity all the way down to 11 and it still hung. 

.\sgminer.exe -k phi2 -o stratum+tcp://letsmine.it:8332 -u MJ12nWE6SooknThr74EpMTSsP7z3hcogHb.worker2 -w 256 -I 21 -p c=AGM --gpu-threads 1

I will add that and post the log file later.

Yes I was getting 3.7 - 3.8mhs until it hung and then that average shown just keeps dropping.

**Comment by ricky24theman** [comment]
here is another where it declared it sick 
[log.txt](https://github.com/fancyIX/sgminer-phi2-branch/files/2570358/log.txt)

**Comment by fancyIX** [comment]
@ricky24theman Also, your fan speed is only 44% and temp is up to 75C. I think you need to set a higher fan speed in any case. 75C temp sounds too high.

**Comment by ricky24theman** [comment]
Thank you for the heads up. Yes, I am aware of that. I usually keep the cards around 62C. Every time it did a hard crash and reboot it reset my Radeon settings to default with the slower fan speed and max temp of 80C. I  jest left it while testing different intensity and watched to make sure it didn't hit 80C.

**Comment by fancyIX** [comment]
@ricky24theman Did the miner hangs with higher fan and lower temp?

**Comment by fancyIX** [comment]
beta5c windows version seems working fine. Problem seems happens from beta5d.

**Comment by fancyIX** [comment]
@ricky24theman Seems that you cannot run other programs when you run this miner. I tried to run it as the only program and didn't seem problem. If I launch another big program, like visual studiio, it hangs immediately. So I guess it hangs when you run other programs.

**Comment by jestercore** [comment]
I have issue too 

https://github.com/Quake4/MindMiner/issues/286

**Comment by fancyIX** [comment]
@jestercore Are you using windows? Are you running other programs while running the miner? Can you add "--debug --log-file log.txt" and upload your log file?

**Comment by jestercore** [comment]
> @jestercore Are you using windows? Are you running other programs while running the miner? Can you add "--debug --log-file log.txt" and upload your log file?

Windows 10. Yes, Mindminer and some background processes like Afterburner and etc. Tried with CPU miner and without - no luck. Yes, gonna upload it's later. System crashing not from running miner, but when i try to CLOSE miner. There is even some hashrate, but it's i can't close without system hang.

**Comment by fancyIX** [comment]
I can reproduce it on windows. Linux works fine. Will investigate.

**Comment by fancyIX** [comment]
@ricky24theman @jestercore : Seems like a compiler bug. I rebuilt the bin files with a newer compiler and see problem doesn't happen. Tested on my Vega56 and 580 running phi2 for 2 hours without crash. It does hang when I run visual studio or when I enable windows sleep display, but I guess that doesn't matter for a mining rig. I've uploaded the fixed file replacing the previous one. Please download it again from the release page and see if that solves your problem. Thanks!

**Comment by jestercore** [comment]
Tried - no luck!

**Comment by fancyIX** [comment]
@jestercore , which driver do you use? I can install it to see what happens.

**Comment by fancyIX** [comment]
@jestercore I installed 18.2.1 and run allium mining about one hour and could not see crash.
![screenshot 7](https://user-images.githubusercontent.com/31875623/48532222-5376ed80-e854-11e8-9c06-1036d4d791fc.png)
![screenshot 6](https://user-images.githubusercontent.com/31875623/48532223-540f8400-e854-11e8-9e25-fa067d3fc2f0.png)

**Comment by jestercore** [comment]
i have 560+580, that's maybe issue

**Comment by fancyIX** [comment]
@jestercore unfortunately I don't' have 560 for testing. If you have time you can try running on 560 only or 580 only to see if it's 560's problem.

**Comment by jestercore** [comment]
I disabled 560 in device manager and.. Yes, now it's working.

**Comment by fancyIX** [comment]
@jestercore , thanks for the heads up. If you have time can you run 560 only to see if crash happens? I don't have 560 for testing so the support for it may be weaker than 580.

**Comment by jestercore** [comment]
[580only.txt](https://github.com/fancyIX/sgminer-phi2-branch/files/2583984/580only.txt)
[560only.txt](https://github.com/fancyIX/sgminer-phi2-branch/files/2583985/560only.txt)
Both cards working separated

**Comment by fancyIX** [comment]
@jestercore , I don't expect any kernel compile happens for allium/lyra2z/phi2. As long as you use -w 256, the prebuilt bin files should be load (no kernel compile).
