### ISSUE TITLE
Study cuda code to see if there is any room for optimization

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#13]

**Comment by KL0nLutiy** [comment]
@fancyIX, could we use uint datatype for states instead of ulong, I found from the cuda code, that they use uint type https://github.com/tpruvot/ccminer/blob/3d03a1b9fd0a14c65f231ed65f9cebb267e63a4f/lyra2/cuda_lyra2.cu
So, maybe we could store more to LDS?

**Comment by fancyIX** [comment]
@KL0nLutiy It seems that the cuda code's smallest compute item is uint2[4]. In the current code we have ulong[4]. So the parallel level doesn't improve and the lds requirement is the same.

**Comment by fancyIX** [comment]
Not much we can do since GCN asm is the real solution.
