### ISSUE TITLE
Older RX model GPU's

### ISSUE THREAD

**Issue by MaynardMiner** [fancyIX/sgminer-phi2-branch#133]
You seem like the man to ask this.

I made a linux profit switching miner (SWARM). It works well, but there seems to be a pattern that older RX model GPU's are failing to work with any sgminer. I am trying to determine the cause.

The failure occurs right at start, when the

```* using Jansson 2.11 screen```

line appears. It doesn't get past that line.

I am using generic start up settings:

``export GPU_MAX_HEAP_SIZE=100``

``export GPU_USE_SYNC_OBJECTS=1``

``export GPU_SINGLE_ALLOC_PERCENT=100``

``export GPU_MAX_ALLOC_PERCENTAGE``

Like I stated, it works great for most Ellesemere gpu's. It seems the older one's won't get past that screen. Like the older RX470 4GB is one I see it happening a lot.

Is there maybe a way for me to debug what is happening in background, to see the issue?

This isn't just your miner- It's all sgminers.

If I can code a fix in sgminer- I'm willing to do so, I just don't know where to start. There are some larger farms that want to use sgminers running older GPU's.

**Comment by fancyIX** [comment]
@MaynardMiner Note that sgminer compiles source code into bin file at the first time it runs. So if user's CPU it weak, it may take several minutes for compile to finish. You just need to wait for it. You can check the CPU usage to see if sgminer is using lots of CPU time, to see if it's compiling.

**Comment by MaynardMiner** [comment]
I am aware of that. I have had to crash course myself pretty hard in how sgminer works. I also know I could compile a debugging version, too I believe....But trying to do it vicariously through users and not directly is not difficult.

I guess it's closing after 30 or seconds after it reaches its line. It physically closes, like it doesn't even reach the part of building the binary, or it crashes before it actually outputs that it is starting the process.

**Comment by MaynardMiner** [comment]
![unknown](https://user-images.githubusercontent.com/38481606/49618304-151dab80-f986-11e8-8ac3-eb45c83330e0.png)


User photo passed to me.

My miner changes the name of sgminer just  before launching, but it is launching sgminer. (A trick I use to track running instances in linux)

**Comment by MaynardMiner** [comment]
Apparently is either hangs right there, or just closes.

**Comment by fancyIX** [comment]
@MaynardMiner If it happens for all  sgminers distributed by you, probably you need to check if there is anything unusual in your distribution.

**Comment by MaynardMiner** [comment]
No. Most users state it works perfectly fine. I have a few users that state that all the sgminers don't work for them.

The two things they all have in common is that they are running older RX series cards in HiveOS (stable image). For everyone else it seems to work fine.

I know that screen shows nothing. I'm waiting for one of them to get me a debug log. I will post when they do.

I just posted here, because I thought maybe you might have heard/known something regarding older RX cards.

**Comment by MaynardMiner** [comment]
I am closing.

I will let you know if a user actually runs debug. I explained them how to do so, nobody has attempted.

It works fine for me.
