### ISSUE TITLE
Zcoin MTP

### ISSUE THREAD

**Issue by KL0nLutiy** [fancyIX/sgminer-phi2-branch#136]
Hello, @fancyIX , could you please add MTP algo for Zcoin
https://zcoin.io/guide-on-how-to-mine-zcoin-xzc/

**Comment by fancyIX** [comment]
Does this mean XZC changed their algo from lyra2Z to MTP? In the link you posted it says sgminer is WIP. Does that mean other guys already started working on it? It seems MTP is not related to lyra so I will put in in low priority unless there is a bounty.

**Comment by fancyIX** [comment]
Seems the deadline for bounty has passed long time ago...

**Comment by fancyIX** [comment]
https://github.com/zcoinofficial/sgminer
Seems there are ulong[128] LDS array shared by 32 threads. The potential speed up by cross lane sharing may be significant.

**Comment by fancyIX** [comment]
Feature done. Will improve later
