### ISSUE TITLE
Investigate cuckoo cycles

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#150]
Refer to https://github.com/mimblewimble/grin-miner
https://github.com/meritlabs/merit-miner

**Comment by fancyIX** [comment]
LDS is not a limit, so dpp instructions may not help much. Seems not worth doing.

**Comment by yuzi-co** [comment]
considering there is no proper windows amd miner for cuckoo, maybe it is worth it ;)

**Comment by fancyIX** [comment]
@yuzi-co doesn’t Bminer support windows?

**Comment by MaynardMiner** [comment]
User base really needs a cuckaroo29 miner that can support nicehash and compile in linux.

https://github.com/mozkomor/GrinGoldMiner/blob/master/src/OclSolver/kernel.cl

Someone already wrote a kernel for AMD.

**Comment by fancyIX** [comment]
@MaynardMiner Thanks for the info. Will work on it once I have time...
