### ISSUE TITLE
ethash: support non-standard stratum protocol

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#157]

**Comment by yuzi-co** [comment]
Not working with nicehash
"Rejected untracked stratum share from daggerhashimoto.usa.nicehash.com"

I am guessing this fits in this ticket :)

**Comment by fancyIX** [comment]
@yuzi-co yeah... it seems that nicehash has different format of their messages. Also, there are many pools that runs eth protocol, that is different from standard stratum and different from nicehash too.

**Comment by fancyIX** [comment]
https://github.com/sammy007/open-ethereum-pool/blob/master/docs/STRATUM.md

**Comment by fancyIX** [comment]
Seems most pools already switched from eth protocol to standard
