### ISSUE TITLE
Investigate argon2d

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#158]
could implement argon2d250 and argon2d500 for amd gpu

this person was able to do it based off of ccminer-opt by jayddee.

https://bitcointalk.org/index.php?topic=5053255.0

https://github.com/bogdanadnan/multiminer

**Comment by yuzi-co** [comment]
even better one:
https://github.com/duality-solutions/Dynamic-GPU-Miner-AMD

**Comment by fancyIX** [comment]
@yuzi-co thanks for the info. Seems like there are lots of shuffling. I can apply GCN cross lane instructions to speed it up. (only if I have time to work on it...)

**Comment by yuzi-co** [comment]
And if you can also add the 250 and 4096 variants ;)
I tried modifying it for 250, but failed, beyond basic algo parameters, there must be something else

**Comment by alucard20724** [comment]
i was just about to point out, but @yuzi-co got it for Dynamic.
Dynamic is better.
vega64 @ 155 khash
vega56 @ 140 khash
RX580 @ 90 khash
RX570 @ 80 khash
RX560 @ 35 khash
each where just set with -g 2 parameter.

**Comment by fancyIX** [comment]
@alucard20724 I modified Dynamic-GPU-Miner-AMD a bit by altering LDS shuffling with GCN cross lane instruction. My version of sgminer may be a little bit faster (or slower). Welcome to test

**Comment by alucard20724** [comment]
@fancyIX speed on vega64 are impressive.  @180 khash.
I'll check the rest of the cards this weekend when i have more time

**Comment by alucard20724** [comment]
@fancyIX  for the rx580 i get @80khash and with the rx560, i get @32khash... all were done with just the -g 2 parameter.

Definately a big boost with the vegas.  I'll test the vega56 later.... need to head to bed.

**Comment by yuzi-co** [comment]
I get a slight speed improvement on RX480 (94 to 98k)

**Comment by fancyIX** [comment]
@alucard20724 for 580 you need to wait a few minutes. It may ramp up to 90+
