### ISSUE TITLE
Support Bitcore(Timetravel10) algo

### ISSUE THREAD

**Issue by kr1z1s** [fancyIX/sgminer-phi2-branch#165]
VERY LOW hashrate on NEW Vega cards with sgminer - https://github.com/bitbandi/sgminer-timetravel

Please add kernel for Bitmark(Timetravel10)

**Comment by fancyIX** [comment]
@kr1z1s do you happen to know which .cl file to take a look at? I cannot find any file like timetravel.cl

**Comment by kr1z1s** [comment]
[time10.zip](https://github.com/fancyIX/sgminer-phi2-branch/files/2820429/time10.zip)

**Comment by fancyIX** [comment]
@kr1z1s not sure if cross lane instructions can speed it up. Let me know if you have any hints

**Comment by kr1z1s** [comment]
> @kr1z1s not sure if cross lane instructions can speed it up. Let me know if you have any hints

I do not know. My Vega64 hashrate - 18 Mh. At the same time, it is not loaded at all.

**Comment by fancyIX** [comment]
seems not feasible for applying cross instructions to speed up performance.
