### ISSUE TITLE
verushash

### ISSUE THREAD

**Issue by MaynardMiner** [fancyIX/sgminer-phi2-branch#179]
https://github.com/monkins1010/AMDVerusCoin/blob/master/verus.cl

I know you are busy, but this miner doesn't work well. It would be awesome if you could find a way to integrate it into sgminer.

**Comment by fancyIX** [comment]
Seems not feasible to speed up with cross lane instructions.

**Comment by MaynardMiner** [comment]
I'm not interested in speeding up.

It does't work. I can't use it. It locks up rigs, no matter how I try to edit / follow instructions...And when I do get it to work (before hard crashing)- It fails to connect to any pool on yiiimp framework.

It's the miner itself, not the kernel that is issue.

**Comment by MaynardMiner** [comment]
There are no other miners but this one...Pretty sure it doesn't support Vega's either.

That was why I was requesting.
