### ISSUE TITLE
Radeon VII - Low Hash Rate

### ISSUE THREAD

**Issue by solidappconsulting** [fancyIX/sgminer-phi2-branch#185]
I'm mining XZC with one Radeon VII. I have only been able to get a hash rate of ~2.2Mh/s and from what I've read online I should be getting ~3.3Mh/s or at least that what other have using Windows.

I've tried changing the settings with no luck. Here's what I use now: ./sgminer --kernel mtp_vega --intensity 22

Is there anything I can do to increase my hash rate?

Thanks

**Comment by fancyIX** [comment]
@solidappconsulting I don’t have time to improve Vega speed. Can you ask official sgminer author? See https://github.com/zcoinofficial/sgminer/releases

**Comment by solidappconsulting** [comment]
"--worksize 64" increased the hash rate.

**Comment by fancyIX** [comment]
@solidappconsulting nice. You are using my branch or the official branch?

**Comment by solidappconsulting** [comment]
I'm trying to find the best one right now. I'm having mixed results with both the miners and the pools not reporting comparable hash rates. When I find a good match I'll let you know.

**Comment by solidappconsulting** [comment]
I can tell you that the official branch doesn't show the correct hash rate. I have two videos cards right now and the different mining pool websites are showing hash rates for one. Your version is showing a more correct hash rate. However there seems to be more hash rate fluctuations with this version...
