### ISSUE TITLE
GPU order match PCI Bus (Windows)

### ISSUE THREAD

**Issue by MaynardMiner** [fancyIX/sgminer-phi2-branch#186]
90.0000 89.0000 90.0000 117.0000
  580       580         580      Vega64

Is the order I am getting from miner

Vega64  580 580  580

Is the order of the PCI bus in windows.

This is problem that happens with other miners as well- Do you have a suggestion on how to fix? Maybe a setting I can set prior to launching the miner?

I'm just curious if you have some wisdom on the matter.

**Comment by fancyIX** [comment]
Sorry I don't know. Need to read some code to know. But no time.
