### ISSUE TITLE
still getting errors when try to build

### ISSUE THREAD

**Issue by vvaske** [fancyIX/sgminer-phi2-branch#189]
Error	13	error LNK2005: json_sprintf already defined in config_parser.obj	C:\sgminer-phi2-branch-5.6.1.3.b5ip3\winbuild\jansson.lib(value.obj)

Error	14	error LNK2001: unresolved external symbol __acrt_iob_func	C:\sgminer-phi2-branch-5.6.1.3.b5ip3\winbuild\pdcurses.lib(initscr.obj)

Error	16	error LNK2001: unresolved external symbol __stdio_common_vfprintf	C:\sgminer-phi2-branch-5.6.1.3.b5ip3\winbuild\pdcurses.lib(initscr.obj)

Error	21	error LNK1120: 3 unresolved externals	C:\sgminer-phi2-branch-5.6.1.3.b5ip3\winbuild\output\x64\Release\sgminer.exe

**Comment by fancyIX** [comment]
@vvaske for the first error, you can just rename function "json_sprintf" to something else in config_parser.c
For other errors, seems like your pdcurses.lib lacks some dependency that is not included in your project

**Comment by vvaske** [comment]
new errors

     1>adl.obj : error LNK2001: unresolved external symbol stdscr
     1>adl.obj : error LNK2001: unresolved external symbol wgetch
     1>driver-opencl.obj : error LNK2001: unresolved external symbol immedok
     1>sgminer.obj : error LNK2001: unresolved external symbol waddch
     1>sgminer.obj : error LNK2001: unresolved external symbol init_pair
     1>sgminer.obj : error LNK2001: unresolved external symbol leaveok
     1>sgminer.obj : error LNK2001: unresolved external symbol echo
     1>sgminer.obj : error LNK2001: unresolved external symbol wattrset
     1>sgminer.obj : error LNK2001: unresolved external symbol start_color
     1>sgminer.obj : error LNK2001: unresolved external symbol wrefresh
     1>sgminer.obj : error LNK2001: unresolved external symbol noecho
     1>sgminer.obj : error LNK2001: unresolved external symbol wclrtoeol
     1>sgminer.obj : error LNK2001: unresolved external symbol wgetnstr
     1>sgminer.obj : error LNK2001: unresolved external symbol wmove
     1>sgminer.obj : error LNK2001: unresolved external symbol cbreak
     1>sgminer.obj : error LNK2001: unresolved external symbol refresh
     1>sgminer.obj : error LNK2001: unresolved external symbol nocbreak
     1>sgminer.obj : error LNK2001: unresolved external symbol touchwin
     1>sgminer.obj : error LNK2001: unresolved external symbol newwin
     1>sgminer.obj : error LNK2001: unresolved external symbol wclear
     1>sgminer.obj : error LNK2001: unresolved external symbol scrollok
     1>sgminer.obj : error LNK2001: unresolved external symbol idlok
     1>sgminer.obj : error LNK2001: unresolved external symbol LINES
     1>sgminer.obj : error LNK2001: unresolved external symbol halfdelay
     1>sgminer.obj : error LNK2001: unresolved external symbol mvwprintw
     1>sgminer.obj : error LNK2001: unresolved external symbol wattroff
     1>sgminer.obj : error LNK2001: unresolved external symbol initscr
     1>sgminer.obj : error LNK2001: unresolved external symbol getmaxx
     1>sgminer.obj : error LNK2001: unresolved external symbol wattron
     1>sgminer.obj : error LNK2001: unresolved external symbol wprintw
     1>sgminer.obj : error LNK2001: unresolved external symbol erase
     1>sgminer.obj : error LNK2001: unresolved external symbol mvwin
     1>sgminer.obj : error LNK2001: unresolved external symbol endwin
     1>sgminer.obj : error LNK2001: unresolved external symbol wresize
     1>sgminer.obj : error LNK2001: unresolved external symbol delwin
     1>sgminer.obj : error LNK2001: unresolved external symbol mvwhline
     1>sgminer.obj : error LNK2001: unresolved external symbol getmaxy

**Comment by fancyIX** [comment]
@vvaske do you have discord id? mine: fancyIX#4494
We can talk there
