### ISSUE TITLE
about phi2-sc variant...

### ISSUE THREAD

**Issue by tpruvot** [fancyIX/sgminer-phi2-branch#2]
This part should be modified to run on 144 input :

https://github.com/fancyIX/sgminer-phi2-branch/blob/cbbdbf935cb273d0d0acf91c0ec2f056c5be6e71/util.c#L1604

phi2hash() func too
```
+       uint64_t* in64 = (uint64_t*)(input);
+       bool has_roots = in64[11] != 0;
+
        sph_cubehash512_init(&ctx_cubehash);
-       sph_cubehash512(&ctx_cubehash, input, false ? 144 : 80);
+       sph_cubehash512(&ctx_cubehash, input, has_roots ? 144 : 80);
```

**Comment by tpruvot** [comment]
you can debug/work on this branch: https://github.com/tpruvot/sgminer/tree/phi2

**Comment by fancyIX** [comment]
@tpruvot Dude, I know most of my code are from other open source project. But I did see lots of my code in your branch. So at least please mention my nick name...?

**Comment by tpruvot** [comment]
there is nothing working for now...

**Comment by fancyIX** [comment]
Should be working now.

**Comment by tpruvot** [comment]
Indeed, and i found my mistake too

**Comment by tpruvot** [comment]
you can test phi2-sc here with these settings:

      "name":"LUX Testnet",
      "priority": "0",
      "url": "stratum+tcp://dev.ccminer.org:8332",
      "user": "test",
      "pass": "c=LUXT"

For now my fork only works on nvidia... not on the vega56. which hardware do you own ?

**Comment by fancyIX** [comment]
@tpruvot I tested on Vega56 and RX 580
