### ISSUE TITLE
so slow hashrate at AMD RX580 4gb Ubuntu

### ISSUE THREAD

**Issue by khunpoum** [fancyIX/sgminer-phi2-branch#20]
~800 khs at RX570/580 4gb

so slow hashrate, what is wrong?

amdgpu-pro 17.40
sgminer compiled from commit 844f29b  (current master branch)

```
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_MAX_ALLOC_PERCENT=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_MAX_HEAP_SIZE=100

./sgminer -k phi2 -w 32 -I 20 -o stratum+tcp://eu.bsod.pw:11518 -u LVC5XVtxhm3awsaJBVgvE3SsEprHQTXy1D -p c=LUX

```

<img width="589" alt="pasted_image_8_14_18__8_43_pm" src="https://user-images.githubusercontent.com/29778875/44108382-df6e3626-a002-11e8-8575-9e84d47f9b91.png">

**Comment by KL0nLutiy** [comment]
@fancyIX, there is one more pattern for lyra2 algo: https://github.com/KL0nLutiy/sgminer-kl/blob/master/kernel/lyra2REv2.mdz.cl, maybe it will be faster?

**Comment by fancyIX** [comment]
@KL0nLutiy, nice, will try

**Comment by KL0nLutiy** [comment]
@fancyIX, yes it is faster, also you could use wolf-echo and wolf-skein from https://github.com/KL0nLutiy/sgminer-kl/blob/master/kernel/x16.cl, it's much faster.

**Comment by fancyIX** [comment]
@KL0nLutiy now it's much faster, but still not good enough. Any idea how to push it further?

**Comment by KL0nLutiy** [comment]
What about the lycl pattern? Is it slower than mdz?

**Comment by fancyIX** [comment]
@KL0nLutiy It's a little bit slower.

**Comment by fancyIX** [comment]
@KL0nLutiy the code is https://github.com/fancyIX/sgminer-phi2-branch/tree/feature/%2312

**Comment by KL0nLutiy** [comment]
@fancyIX, compiled that branch, but could not start miner failed during building binary with no errors.
Use this bat:

setx GPU_FORCE_64BIT_PTR=0
setx GPU_USE_SYNC_OBJECTS=1
setx GPU_MAX_ALLOC_PERCENT=100
setx GPU_SINGLE_ALLOC_PERCENT=100
setx GPU_MAX_HEAP_SIZE=100

sgminer.exe -k phi2 -o stratum+tcp://yiimp.eu:8332 -u LfV448zDbNezd8EEVGgVcju2qJNtyfC1n8.worker2 -p donate -I 18 -w 64 -g 1 -d 1 --log-file log.txt
pause

**Comment by fancyIX** [comment]
@KL0nLutiy  what does log.txt say?

**Comment by KL0nLutiy** [comment]
[log.txt](https://github.com/fancyIX/sgminer-phi2-branch/files/2295076/log.txt)

**Comment by fancyIX** [comment]
@KL0nLutiy "Failed to ADL_Overdrive5_ODPerformanceLevels_Get". Maybe it's irrelevant but you can try disable ADL

**Comment by KL0nLutiy** [comment]
@fancyIX, no it is always like this

**Comment by fancyIX** [comment]
@KL0nLutiy I tried it and it can run on my vega 56 on ubuntu 18.04. Maybe you forgot to make clean or remove .bin file?

**Comment by fancyIX** [comment]
@KL0nLutiy Or, maybe my sgminer cannot run with your env at all, not specific to that branch. Did you try master branch?

**Comment by KL0nLutiy** [comment]
Master branch is working I test it with rx 580 8gb on windows, no .bin files in the folder

**Comment by KL0nLutiy** [comment]
@fancyIX, could you please attech compiled miner with lycl pattern?

**Comment by fancyIX** [comment]
Windows or Linux? I guess windows version, right?

Regards!
   Changdao from cell phone

**Comment by fancyIX** [comment]
@KL0nLutiy I tried windows build but it cannot run, exits during compiling. Linux build works for me. Strange.

**Comment by KL0nLutiy** [comment]
@fancyIX, same behavior

**Comment by fancyIX** [comment]
May I know why you need compiled #12 branch? I will try to figure out why
it cannot run on windows.

**Comment by fancyIX** [comment]
@KL0nLutiy I just realized that branch is behind and cannot work with newest luxcore. Fixed. You can try newest code now.

**Comment by fancyIX** [comment]
Vega performance now is much faster:

![vega56](https://user-images.githubusercontent.com/31875623/44298144-6cdabe80-a292-11e8-8287-c67a365aa084.png)

**Comment by KL0nLutiy** [comment]
Just an idea for speed improvment, maybe split mdz kernel into 3 part like lycl pattern

**Comment by KL0nLutiy** [comment]
Also midstate for cubehash can be added

**Comment by KL0nLutiy** [comment]
@fancyIX, did you saw this pattern?
[lyra2.zip](https://github.com/fancyIX/sgminer-phi2-branch/files/2299929/lyra2.zip)

**Comment by fancyIX** [comment]
@KL0nLutiy Thanks for the suggestion. That code is good for lyra2rev2, but seems not good for lyra2, since lyra2 requires 4x more memory of the matrix

**Comment by fancyIX** [comment]
@KL0nLutiy about that new pattern, did you get chance to try it? It should be better than the original mdz pattern since more local memory is used to store matrix instead of global mem. But I don't know  if it's better in lyra2 case. I will try it anyway. BTW, where did you find it?

**Comment by KL0nLutiy** [comment]
@fancyIX, no I did not try it, find compiled version on chinese forum.

**Comment by fancyIX** [comment]
Now hashrate of RX 580 is about 1.3Mhs and Vega 64 is about 2.6Mhs

**Comment by fancyIX** [comment]
No long "so slow"
