### ISSUE TITLE
tpruvot optimizations

### ISSUE THREAD

**Issue by KL0nLutiy** [fancyIX/sgminer-phi2-branch#22]
Found some optimizations from tpruvot:
https://github.com/tpruvot/sgminer/commit/fc3ef0850fe9ec9212ac299414e0e9a9a4b6d352
https://github.com/tpruvot/sgminer/commit/da03e8e62c5c0f0fa354e442faa774cc819c6050

**Comment by fancyIX** [comment]
@KL0nLutiy , the first one is already done. The second one my not worth trying, but I will try.
