### ISSUE TITLE
Slow hashspeeds

### ISSUE THREAD

**Issue by MLity7** [fancyIX/sgminer-phi2-branch#225]
I hope this is the right place to get some help, i was directed here. I'm mining using sgminer and i'm only getting about 2mh/s. I'm using a 5700xt. I've been told I should be getting more than that but i can't seem to get it any higher.

This is what i'm using:

setx GPU_FORCE_64BIT_PTR 1

setx GPU_USE_SYNC_OBJECTS 1

setx GPU_MAX_ALLOC_PERCENT 95

setx GPU_SINGLE_ALLOC_PERCENT 95

setx GPU_MAX_HEAP_SIZE 95

.\sgminer.exe -k allium -o stratum+tcp://freshgarlicblocks.net:3032 -u GVwyL4zh1sA3iVJsW85h46xnd8KUF9d374 -I 23 -p x

**Comment by fancyIX** [comment]
@MLity7 yes... Navi is not well supported yet. Let me take some time to see if I can fix it soon.

**Comment by MLity7** [comment]
Okay, thank you for responding I appreciate it.

**Comment by fancyIX** [comment]
@MLity7 updated a new release: https://github.com/fancyIX/sgminer-phi2-branch/releases/tag/0.7.3-0
Run:
.\sgminer.exe -k allium_navi -o stratum+tcp://freshgarlicblocks.net:3032 -u GVwyL4zh1sA3iVJsW85h46xnd8KUF9d374 -I 23 -p x
(i.e. add _navi to algo name)
I didn't test on 5700xt. On my 6900xt it works well.
