### ISSUE TITLE
Please add support verushash algorithm

### ISSUE THREAD

**Issue by Saikatsaha1996** [fancyIX/sgminer-phi2-branch#235]
Please add support without -pthread cancel disable
-pthread cancel enable
So we can compile in android os...
Android doesn't support pthread cancel..

Help wanted!

**Comment by fancyIX** [comment]
The purpose of this project is for AMD GPU. Android is not supported.

**Comment by Saikatsaha1996** [comment]
Ohhh but actually ./autogen.sh showing OpenCL found gpu mining enable..
But got only make error..
☹️

**Comment by Saikatsaha1996** [comment]
![Screenshot_2021-07-12-23-26-25-103_com termux](https://user-images.githubusercontent.com/72664192/128767143-063b79da-e999-4a44-b156-8bf525b70ecd.jpg)

**Comment by Saikatsaha1996** [comment]
Because android does not support pthread cancel..

**Comment by Saikatsaha1996** [comment]
> The purpose of this project is for AMD GPU. Android is not supported.

@fancyIX  I solved pthread-cancel problem but getting new error.. please give me solution..

![Screenshot_2022-05-07-04-01-38-040_com termux](https://user-images.githubusercontent.com/72664192/167224347-7c5a74e7-917b-47b4-93c0-47a40aa14217.jpg)
![Screenshot_2022-05-07-04-03-51-739_com termux](https://user-images.githubusercontent.com/72664192/167224364-987c02bc-b957-41e4-9c7a-1e8dfdf30e30.jpg)

**Comment by Saikatsaha1996** [comment]
@fancyIX Please add support verushash algorithm.. can you add support ?

**Comment by fancyIX** [comment]
@Saikatsaha1996 Do you have link to existing open source miner that supports verushash?

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 Do you have link to existing open source miner that supports verushash?

Yes @fancyIX sir official
for `AMD-GPU` only .. but now not working pool error
https://github.com/monkins1010/amdveruscoin

For `CPU` && `GPU-CUDA` `ccminer`
https://github.com/monkins1010/ccminer

Mey be you need 
https://github.com/monkins1010/ccminer/tree/Verus2.2/verus

Meybe Sir you can add .. and yes i am requesting you if it possible please reply me back..

Thank you

**Comment by Saikatsaha1996** [comment]
@fancyIX  😊🙏 thank you

**Comment by Saikatsaha1996** [comment]
@fancyIX any update sir?

**Comment by fancyIX** [comment]
@Saikatsaha1996 no time to work on this, but I roughly tooked at the code and cannont think out a way to improve the performace.

**Comment by Saikatsaha1996** [comment]
> @Saikatsaha1996 no time to work on this, but I roughly tooked at the code and cannont think out a way to improve the performace.

Okay sir not a problem.. but when you free .. please add .. thank you so much

**Comment by Saikatsaha1996** [comment]
@fancyIX sir how to mine scrypt n2 Coin?

I mean how to use parameters for scrypt n2?
`--nfactor` = 2 ?
Help wanted
Thank you

**Comment by Saikatsaha1996** [comment]
Sir how to solve?
```
[00:48:19] Algorithm blake2s not found, using ckolivas.
```

I used `-k blake2s`

**Comment by Saikatsaha1996** [comment]
Dear Sir!
If i ask you for helping with unofficial somthing..
Can you help me? 

### Miner related but Fully unofficial..

I know you are `Developer` & i also know developer's don't have time for noob..

But i want help because i don't have any computer language skills..

I want help without any profit..
If you can please reply me for help..
Or if you don't want to help you can ignore as spam msg 🥲
