### ISSUE TITLE
No option for "_Navi" in Hive OS

### ISSUE THREAD

**Issue by rhyno78** [fancyIX/sgminer-phi2-branch#243]
I tried mine neoscrypt-xaya in hiveos but there's no option for neoscrypt-xaya_navi on hiveos and I already choose the fancyix fork, is there any way to add that manually on hiveos? I also can't input additional parameter like -s 1 -g 1 there. I use RX 6900 @fancyIX

**Comment by fancyIX** [comment]
I don't have control on hiveos.
You need to ask them. Like at here:
https://forum.hiveos.farm

**Comment by rhyno78** [comment]
@fancyIX I will mine first on Windows then. thank you. you are the only miner that works with Navi 👍
