### ISSUE TITLE
I found this in GRLC coin discord maybe you are interested

### ISSUE THREAD

**Issue by rhyno78** [fancyIX/sgminer-phi2-branch#246]
https://garlicsquire.com/listing/new-allium-mining-software/
it would be great to achieve more than 30mh/s on this algo since you already support navi gpus

**Comment by fancyIX** [comment]
I know that. Have a WIP
https://github.com/fancyIX/ccminer
It's much faster than original ccminer with pre-30xx cards. For RTX 30xx cards it's not easy to get such huge performance boost.

**Comment by rhyno78** [comment]
@fancyIX okay I'll wait for navi gpus optimisation too :) thank you

**Comment by rhyno78** [comment]
@fancyIX how do you achieve allium on RX 6900 at 24mh/s? I tried overclocking until 2250mhz still not getting 24mh/s… peaked at around 21.4-21.5mh/s

**Comment by fancyIX** [comment]
> @fancyIX how do you achieve allium on RX 6900 at 24mh/s? I tried overclocking until 2250mhz still not getting 24mh/s… peaked at around 21.4-21.5mh/s

Which version did you run? My card is sapphire nitro+. Not sure if that’s faster than normal models

**Comment by rhyno78** [comment]
@fancyIX 0.7.6. mine also sapphire nitro. my driver is 21.9.1

**Comment by rhyno78** [comment]
<img width="286" alt="ss" src="https://user-images.githubusercontent.com/90557972/142965469-d4f585c7-1cbb-4935-9052-b63d551d1f34.PNG">
<img width="287" alt="ss2" src="https://user-images.githubusercontent.com/90557972/142965472-a164f7c8-90d2-47a0-b78f-3c43ddfcf513.PNG">
<img width="421" alt="allium2" src="https://user-images.githubusercontent.com/90557972/142965473-96ad1969-bb42-4beb-be30-210de34c4d62.PNG">
<img width="415" alt="allium1" src="https://user-images.githubusercontent.com/90557972/142965474-59e6ec28-e2c6-418c-98c4-d93eb42ba8c6.PNG">
@fancyIX

**Comment by fancyIX** [comment]
@rhyno78 may be you can try newest driver. Remember to remove any bin files in same folder of seminar.exe

**Comment by rhyno78** [comment]
@fancyIX I already tried your solution. now use 21.10.2 whql. already deleted the bin files in the same folder of sgminer.exe... still stuck at 21.8mh/s-22mh/s

**Comment by fancyIX** [comment]
@rhyno78 this is what I got:
<img width="1916" alt="Screenshot 2021-11-22 213755" src="https://user-images.githubusercontent.com/31875623/142976132-67bed65b-1fb7-4229-813e-ba064afc37ac.png">

**Comment by rhyno78** [comment]
@fancyIX do you clock it above 2300mhz?

**Comment by fancyIX** [comment]
> @fancyIX do you clock it above 2300mhz? or have radeon SAM enabled? my motherboard doesn't support SAM

I didn't change default setting. No OC

**Comment by rhyno78** [comment]
@fancyIX yes but i did undervolted it (around 800v) and clocked to 2050. I got 120watt at 20mh/s. memory clock is not important in this algo

**Comment by rhyno78** [comment]
@fancyIX i see now. this algo need more power to reach 24mh/s. if i use default i also got 23.8-24mh/s

**Comment by fancyIX** [comment]
> @fancyIX yes but i did undervolted it (around 800v) and clocked to 2050. I got 120watt at 20mh/s. memory clock is not important in this algo. another i use is 2250mhz with undervolt around 875-900 (this yield max at 21.8-22mh/s at 150watt)

Depending on implementation, it can require faster memory or not. Current implementation of lyra2 stores data in registers, so memory is not important.
