### ISSUE TITLE
Auto detect navi cards

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#253]
instead of let user specify _navi parameter

**Comment by rhyno78** [comment]
@fancyIX hiveos finally adding _navi suffix but… now there’s another problem… is there any way for me to add this manually?
![F77C7655-38EB-4627-9F33-84918C758B44](https://user-images.githubusercontent.com/90557972/144550411-143d9ea9-9ff8-4790-9459-87c41f630ff6.jpeg)

**Comment by UselessGuru** [comment]
Tested. Works well in 0.9.4
