### ISSUE TITLE
Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)

### ISSUE THREAD

**Issue by mikemulhearn** [fancyIX/sgminer-phi2-branch#257]
I'm attempting to run version 0.8.0 to mine oBTC (Heavyhash algo) on HiveOS, but I'm receiving an error when the miner starts. 

GPU 0 and 1 are Vega 56s, GPU 2 is a RX470, GPU 3-6 are RX570s.

> sgminer 0.8.0-3 - Started: [2021-12-13 12:01:13] - [0 days 00:00:06] 
> 
> ST: 2 SS: 0 NB: 1 LW: 13 GF: 0 RF: 0 
> Connected to heavyhash.na.mine.zergpool.com (stratum) diff 0.200 as user <redacted>
> 
> Block: 1615eba6... Diff:138K Started: [12:01:11] Best share: 0 
> [P]ool management [G]PU management [S]ettings [D]isplay options [Q]uit GPU 0: | OFF / 0.000h/s | R: 0.0% HW:0 WU:0.000/m xI:256 
> GPU 1: | OFF / 0.000h/s | R: 0.0% HW:0 WU:0.000/m xI:256 
> GPU 2: | OFF / 0.000h/s | R: 0.0% HW:0 WU:0.000/m xI:256 
> GPU 3: | OFF / 0.000h/s | R: 0.0% HW:0 WU:0.000/m xI:256 
> GPU 4: | OFF / 0.000h/s | R: 0.0% HW:0 WU:0.000/m xI:256
> 
> [2021-12-13 12:01:12] Initialising kernel heavyhash.cl with nfactor 10, n 1024
> [2021-12-13 12:01:12] initCl() finished. Found Ellesmere
> [2021-12-13 12:01:12] Init GPU thread 4 GPU 4 virtual GPU 4
> [2021-12-13 12:01:12] CL Platform vendor: Advanced Micro Devices, Inc.
> [2021-12-13 12:01:12] CL Platform name: AMD Accelerated Parallel Processing
> [2021-12-13 12:01:12] CL Platform version: OpenCL 2.1 AMD-APP (3180.7)
> [2021-12-13 12:01:12] Platform devices: 5
> [2021-12-13 12:01:12]   0       Ellesmere
> [2021-12-13 12:01:12]   1       Ellesmere
> [2021-12-13 12:01:12]   2       Ellesmere
> [2021-12-13 12:01:12]   3       Ellesmere
> [2021-12-13 12:01:12]   4       Ellesmere
> [2021-12-13 12:01:12] List of devices:
> [2021-12-13 12:01:12]   0       Ellesmere
> [2021-12-13 12:01:12]   1       Ellesmere
> [2021-12-13 12:01:12]   2       Ellesmere
> [2021-12-13 12:01:12]   3       Ellesmere
> [2021-12-13 12:01:12]   4       Ellesmere
> [2021-12-13 12:01:12] Selected 4: Ellesmere
> [2021-12-13 12:01:12] Maximum work size for this GPU (4) is 256.
> [2021-12-13 12:01:12] Your GPU (#4) has 32 compute units, and all AMD cards in the 7 series or newer (GCN cards)                have 64 shaders per compute unit - this
>  means it has 2048 shaders.
> [2021-12-13 12:01:12] Initialising kernel heavyhash.cl with nfactor 10, n 1024
> [2021-12-13 12:01:12] initCl() finished. Found Ellesmere
> [2021-12-13 12:01:13] Work update message received
> [2021-12-13 12:01:13] Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)
> [2021-12-13 12:01:13] Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)
> [2021-12-13 12:01:13] GPU 1 failure, disabling!                                                                                                                        
> [2021-12-13 12:01:13] Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)                                                                         
> [2021-12-13 12:01:13] GPU 3 failure, disabling!                                                                                                                        
> [2021-12-13 12:01:13] GPU 0 failure, disabling!                                                                                                                        
> [2021-12-13 12:01:13] Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)                                                                         
> [2021-12-13 12:01:13] GPU 4 failure, disabling!                                                                                                                        
> [2021-12-13 12:01:13] Error -5: Enqueueing kernel onto command queue. (clEnqueueNDRangeKernel)                                                                         
> [2021-12-13 12:01:13] GPU 2 failure, disabling!

Any ideas what is causing this issue and how I can resolve it?

**Comment by mikemulhearn** [comment]
I replaced the HiveOS 0.8.0 binary with the Github Linux release 0.8.1 binary and I'm no longer receiving that error

**Comment by fancyIX** [comment]
The error code says out of resource. I suspect your work group size is big
