### ISSUE TITLE
Neoscrypt not working in 0.9.3  

### ISSUE THREAD

**Issue by AleRosales** [fancyIX/sgminer-phi2-branch#277]
![menu](https://user-images.githubusercontent.com/32271477/165206914-019830fe-37b3-4af9-9146-b1488ceebadf.jpg)

**Comment by AleRosales** [comment]
use the default .bat

setx GPU_FORCE_64BIT_PTR 1
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
setx GPU_MAX_HEAP_SIZE 100

.\sgminer -k neoscrypt -o hub.miningpoolhub.com:20510 -u fancyIX.worker0 -p x -I 17 -s 1

**Comment by fancyIX** [comment]
@AleRosales did you try other version?

**Comment by AleRosales** [comment]
in version 0.9.1 it works

**Comment by UselessGuru** [comment]
Can confirm Neoscrypt in 0.9.3 is broken. 0.9.2 is OK.

**Comment by UselessGuru** [comment]
Works well in 0.9.4
