### ISSUE TITLE
mining neoscrypt-xaya dont work (Windows/Ubuntu(hiveOs)

### ISSUE THREAD

**Issue by Timialiasmrmining** [fancyIX/sgminer-phi2-branch#282]
Hi I tried all version of your hard fork miner but i never can run it. not on hive OS or ubuntu ore windows
Example in windows i get code Msvcr120.dll
i had a german youtube channel mr mining and want too produce a tutorial with amd GPU ( for Coin Xaya) maybe you can contact me @btmobilstrom@gmail.com
Thanks

**Comment by fancyIX** [comment]
Please check “fix 2” in https://www.drivereasy.com/knowledge/best-solutions-to-fix-msvcr120-dll-is-missing-in-windows/amp/#Solution1
