### ISSUE TITLE
Try use LDS to store matrix instead of global memory

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#31]
Each matrix has 192 ulong, each slot has 4 matrix, each CU has 32KiB, so maximum slots per LDS is about 5. Thus, as long as we keep 4 x 5 work group, the LDS is sufficient.

**Comment by KL0nLutiy** [comment]
@fancyIX, as I understand from Instruction Set, Polaris has 32KiB of LDS, but vega has 64KiB, so maximum slots per LDS on vega can be doubled.
http://developer.amd.com/wordpress/media/2013/12/AMD_GCN3_Instruction_Set_Architecture_rev1.1.pdf
https://developer.amd.com/wp-content/resources/Vega_Shader_ISA_28July2017.pdf

**Comment by fancyIX** [comment]
My understanding is that lds is 64 kib but one work group can use up to 32kib. See http://gad.qq.com/gad/20170623/phpKgk6aV.docx. I did have tried double the work group size but it failed on my Vega card.

Regards!
   Changdao from cell phone

**Comment by KL0nLutiy** [comment]
You are right
