### ISSUE TITLE
Support mining allium coins

### ISSUE THREAD

**Issue by fancyIX** [fancyIX/sgminer-phi2-branch#39]

**Comment by fancyIX** [comment]
@KL0nLutiy At least my current lyra2 kernel should be faster than https://github.com/lenis0012/sgminer-gm/blob/master/kernel/allium.cl, right?

**Comment by KL0nLutiy** [comment]
@fancyIX yes must be faster

**Comment by yuzi-co** [comment]
Lyra2h?
https://github.com/djm34/sgminer-msvc2015

**Comment by fancyIX** [comment]
@yuzi-co will do later

**Comment by fancyIX** [comment]
@yuzi-co: you mentioned lyra2h before. I wonder how popular is that algorithm? The only coin I can find is HPP and HPP seems kind of inactive. lyra2h has a 4x larger matrix than lyra2 and even nvidia miners cannot mine it fast.
